.TH "org.zensoftware" 3 "1 Sep 2009" "Version 1.0" "KVC Object" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.zensoftware \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBKVCObject\fP"
.br
.RI "\fIAn implimentation of Objective-C's Key Value coding. By Chris Richards 2009. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "delegate void \fBobserveValueForKey\fP (string forKey, \fBKVCObject\fP forObject, object oldValue, object newValue)"
.br
.RI "\fIDelegate to observe changes in keys. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "delegate void org.zensoftware.observeValueForKey (string forKey, KVCObject forObject, object oldValue, object newValue)"
.PP
Delegate to observe changes in keys. \fBParameters:\fP
.RS 4
\fIforKey\fP The key that was observed.
.br
\fIforObject\fP The object the key belongs to.
.br
\fIoldValue\fP The key's old value.
.br
\fInewValue\fP The key's new value.
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for KVC Object from the source code.
